spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/guardianai
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view : false

managemnet:
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: false

server:
  port: 8080
